apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: quotes-app
  labels:
    app: backend
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  NODE_ENV: "production"
  PORT: "3000"