apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: quotes-app
  labels:
    app: frontend
    tier: web
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 5000
      #nodePort: 30084
  type: LoadBalancer